package com.fixforge.engine.service;


import org.kohsuke.github.GHPullRequest;
import org.kohsuke.github.GHRepository;
import org.kohsuke.github.GitHub;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class GitHubService {

    private final String token;
    private final String defaultBranch;


    public GitHubService(
            @Value("${github.token}") String token,
            @Value("${github.default.branch:main}") String defaultBranch) {

        this.token = token;
        this.defaultBranch = defaultBranch;
    }

    public String createPR(String repoUrl, String branch) throws Exception {

        GitHub github = GitHub.connectUsingOAuth(token);

        String repoFullName = extractRepoFullName(repoUrl);

        GHRepository repository = github.getRepository(repoFullName);

        String prTitle = "AI Code Fix";
        String prBody = buildPRDescription();

        GHPullRequest pr = repository.createPullRequest(
                prTitle,
                branch,
                defaultBranch,
                prBody
        );

        return pr.getHtmlUrl().toString();
    }


    private String extractRepoFullName(String repoUrl) {

        if (repoUrl == null || repoUrl.isEmpty()) {
            throw new IllegalArgumentException("Invalid GitHub URL");
        }


        String cleaned = repoUrl
                .replace("https://github.com/", "")
                .replace(".git", "")
                .trim();

        if (!cleaned.contains("/")) {
            throw new IllegalArgumentException("Invalid GitHub repo format");
        }

        return cleaned;
    }


    private String buildPRDescription() {

        return """
                This pull request was automatically generated by AI.

                Changes include:
                - Bug detection
                - Code fixes applied
                - Potential runtime issue prevention

                 Please review before merging.
                """;
    }
}