server.port=8080

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.options.model=ministral-3:3b
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.chat.options.num-predict=2048
spring.ai.ollama.chat.options.top-k=40
spring.ai.ollama.chat.options.top-p=0.9





# Gemini API
google.ai.api.key=AIzaSyAbtivBj9cFUwcl7gz3emAlyfr6WZJh0mg
gemini.model=models/gemini-2.5-flash