package com.fixforge.engine.configutil;

public interface Prompt {
     String prompt_analyzeWithOllama = """
                You are an expert production support engineer.

                Analyze the following log file and return ONLY JSON.

                {
                 "summary":"",
                 "errors":[],
                 "rootCause":"",
                 "recommendations":[],
                 "additionalNotes":""
                }

                LOG CONTENT:
                """;
    String getPrompt_analyzeWithGemini="""
                You are an expert production support engineer.

                Analyze the following log file and return ONLY JSON.

                {
                  "summary":"",
                  "errors":[],
                  "rootCause":"",
                  "recommendations":[],
                  "additionalNotes":""
                }

                LOG CONTENT:
                """;

String prDesc="""
                This pull request was automatically generated by AI.

                Changes include:
                - Bug detection
                - Code fixes applied
                - Potential runtime issue prevention

                 Please review before merging.
                """;

String oolamaCodeAnalyzerPrompt="""
                You are an expert Java developer.

                STRICT RULES:

                1. Return COMPLETE corrected Java file
                2. DO NOT remove class or structure
                3. DO NOT create duplicate classes
                4. DO NOT add explanation
                5. DO NOT add comments like "Improved code"
                6. Output MUST compile
                7. Only fix actual issues

                Fix:
                - Null checks
                - Divide by zero
                - Resource leaks
                - Syntax issues
                - Hardcoded credentials (replace with env variables)

                VERY IMPORTANT:
                - Keep original class name
                - Keep structure intact
                - Modify ONLY required lines

                RETURN ONLY JAVA CODE

                CODE:
                """;

String geminiPromptCodeAnayzer="""
                You are an expert Java developer.

                STRICT RULES:

                1. Return COMPLETE corrected Java file
                2. DO NOT remove class or structure
                3. DO NOT create duplicate classes
                4. DO NOT add explanation
                5. DO NOT add comments like "Improved code"
                6. Output MUST compile
                7. Only fix actual issues

                Fix:
                - Null checks
                - Divide by zero
                - Resource leaks
                - Syntax issues
                - Hardcoded credentials (replace with env variables)

                VERY IMPORTANT:
                - Keep original class name
                - Keep structure intact
                - Modify ONLY required lines

                RETURN ONLY JAVA CODE

                CODE:
                """;
}
